package com.example.mealplanner.model.repository.community

import com.example.mealplanner.model.CommunityRecipe
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Firestore-backed implementation. Uses `addSnapshotListener` to deliver realtime
 * updates — when ANY device adds / edits / deletes a recipe, every observer's Flow
 * re-emits the new full list.
 *
 * Firestore document layout (collection `community_recipes`):
 *   {
 *     "title": "Grilled Chicken Salad",
 *     "description": "Quick and healthy",
 *     "calories": 420,
 *     "ingredients": "chicken, lettuce, tomato",
 *     "authorEmail": "mirza@example.com",
 *     "authorName": "Mirza",
 *     "timestampMillis": 1717147200000
 *   }
 *
 * Document ID is auto-generated by Firestore on `.add()`.
 */
@Singleton
class CommunityRecipeRepositoryImpl @Inject constructor(
    private val firestore: FirebaseFirestore,
    private val auth: FirebaseAuth
) : CommunityRecipeRepository {

    private val collection get() = firestore.collection(COLLECTION)

    /**
     * Wraps Firestore's `addSnapshotListener` callback in a Kotlin Flow.
     * Each snapshot fires this lambda; the Flow re-emits the mapped list.
     * `awaitClose` removes the listener when the collector cancels — no leaks.
     */
    override fun observeAll(): Flow<List<CommunityRecipe>> = callbackFlow {
        val query = collection.orderBy("timestampMillis", Query.Direction.DESCENDING)

        val registration = query.addSnapshotListener { snapshot, error ->
            if (error != null) {
                close(error)
                return@addSnapshotListener
            }
            val recipes = snapshot?.documents.orEmpty().mapNotNull { doc ->
                runCatching {
                    CommunityRecipe(
                        documentId      = doc.id,
                        title           = doc.getString("title").orEmpty(),
                        description     = doc.getString("description").orEmpty(),
                        calories        = (doc.getLong("calories") ?: 0L).toInt(),
                        ingredients     = doc.getString("ingredients").orEmpty(),
                        authorEmail     = doc.getString("authorEmail").orEmpty(),
                        authorName      = doc.getString("authorName").orEmpty(),
                        timestampMillis = doc.getLong("timestampMillis") ?: 0L
                    )
                }.getOrNull()
            }
            trySend(recipes)
        }

        awaitClose { registration.remove() }
    }

    override suspend fun add(
        title: String,
        description: String,
        calories: Int,
        ingredients: String
    ): Result<Unit> = runCatching {
        val user = auth.currentUser ?: error("You must be logged in to post a recipe.")
        val payload = mapOf(
            "title"           to title.trim(),
            "description"     to description.trim(),
            "calories"        to calories,
            "ingredients"     to ingredients.trim(),
            "authorEmail"     to (user.email ?: ""),
            "authorName"      to (user.displayName?.takeIf { it.isNotBlank() } ?: user.email?.substringBefore('@') ?: "Anonymous"),
            "timestampMillis" to System.currentTimeMillis()
        )
        collection.add(payload).await()
        Unit
    }

    override suspend fun delete(documentId: String): Result<Unit> = runCatching {
        collection.document(documentId).delete().await()
        Unit
    }

    companion object {
        private const val COLLECTION = "community_recipes"
    }
}
